name: Python Pipeline

on: push

jobs:
  test:
    runs-on: ubuntu-lastet
    steps:
      - uses: actions/checkout@v4.2.0
      - run: python hello.py

  build:
    needs: [test]
    runs-on: ubuntu-lastet
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: hello
          path: .
